{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "2.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.8.0.jar",
          "url": "crnet-2.8.0.jar",
          "size": 618739,
          "sha512": "c37eed704dcbdd4c8e1b78652ea94d13f3ccd73cc7138d59d95e5d71697ccd9a72732b7eb5648ff828b0047a9875ea4a99b18394d20b1d371a664a7810079a40",
          "sha256": "9a94587394e46206573680611f37040403dd6c5736e7b6fcc30c748f609cfff7",
          "sha1": "ed69bac699bebbfbf2c8238d5f4f5f4a47cae079",
          "md5": "23f86781817fcb9be6fd11ae5b4545eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.8.0.jar",
          "url": "crnet-2.8.0.jar",
          "size": 618739,
          "sha512": "c37eed704dcbdd4c8e1b78652ea94d13f3ccd73cc7138d59d95e5d71697ccd9a72732b7eb5648ff828b0047a9875ea4a99b18394d20b1d371a664a7810079a40",
          "sha256": "9a94587394e46206573680611f37040403dd6c5736e7b6fcc30c748f609cfff7",
          "sha1": "ed69bac699bebbfbf2c8238d5f4f5f4a47cae079",
          "md5": "23f86781817fcb9be6fd11ae5b4545eb"
        }
      ]
    }
  ]
}
