{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-3.0.6.jar",
          "url": "crnet-3.0.6.jar",
          "size": 622725,
          "sha512": "2eab9a1a17128a6d665299d3a067a497071ee43152a714004a9414da3498d32f31bd80eea1cf0df4e4a6b0962f383137641725e9396b6ec65776e8765933c9fc",
          "sha256": "581ca3e335aee47a52762b7589968db7edf399fccaa580df37f99ca57cbd6e83",
          "sha1": "4a38befdbcc23ef766d4680b0063a748bb26e1dd",
          "md5": "af2bb015461f3011e6dc350983713779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-3.0.6.jar",
          "url": "crnet-3.0.6.jar",
          "size": 622725,
          "sha512": "2eab9a1a17128a6d665299d3a067a497071ee43152a714004a9414da3498d32f31bd80eea1cf0df4e4a6b0962f383137641725e9396b6ec65776e8765933c9fc",
          "sha256": "581ca3e335aee47a52762b7589968db7edf399fccaa580df37f99ca57cbd6e83",
          "sha1": "4a38befdbcc23ef766d4680b0063a748bb26e1dd",
          "md5": "af2bb015461f3011e6dc350983713779"
        }
      ]
    }
  ]
}
