{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "2.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.8.2.jar",
          "url": "crnet-2.8.2.jar",
          "size": 618436,
          "sha512": "cc29b86b54865ddfeb142ab2b9503f68df2362abf240a7c2fde413317806aede4d6a63804ff0498a6f45faa7a84076f3620018b26093dd15d2d9f6435d9435cf",
          "sha256": "25d0f75619f43fba8210143d8f9908694cef5db437d64107eb6a0ea55a243e9e",
          "sha1": "5afe4a2a4927ec571b3a8740a6ff375df4f16773",
          "md5": "ded861d9262881f2ae8a05f887a4f450"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.8.2.jar",
          "url": "crnet-2.8.2.jar",
          "size": 618436,
          "sha512": "cc29b86b54865ddfeb142ab2b9503f68df2362abf240a7c2fde413317806aede4d6a63804ff0498a6f45faa7a84076f3620018b26093dd15d2d9f6435d9435cf",
          "sha256": "25d0f75619f43fba8210143d8f9908694cef5db437d64107eb6a0ea55a243e9e",
          "sha1": "5afe4a2a4927ec571b3a8740a6ff375df4f16773",
          "md5": "ded861d9262881f2ae8a05f887a4f450"
        }
      ]
    }
  ]
}
