{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "2.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.8.2.jar",
          "url": "crnet-2.8.2.jar",
          "size": 618089,
          "sha512": "d696d660e057f75ea38a55e4942452a7f1808de5f981abd494ad4f76ffd55f4a7e6cf96970d7195c98023093eb80d64bb86c15fb9cf3dc54f0c7c8137f37e380",
          "sha256": "420611f6cfd870c588fad631cef9a074e7a9101ea1c9bb71c09aa1798ea82939",
          "sha1": "1cc36823d6ddfd31fbcaf38e28b83dd716a18331",
          "md5": "a63b2354db1e18b7418417939c566332"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.8.2.jar",
          "url": "crnet-2.8.2.jar",
          "size": 618089,
          "sha512": "d696d660e057f75ea38a55e4942452a7f1808de5f981abd494ad4f76ffd55f4a7e6cf96970d7195c98023093eb80d64bb86c15fb9cf3dc54f0c7c8137f37e380",
          "sha256": "420611f6cfd870c588fad631cef9a074e7a9101ea1c9bb71c09aa1798ea82939",
          "sha1": "1cc36823d6ddfd31fbcaf38e28b83dd716a18331",
          "md5": "a63b2354db1e18b7418417939c566332"
        }
      ]
    }
  ]
}
