{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.saunhardy",
          "module": "createrington-dev-api",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.6.0.jar",
          "url": "crnet-2.6.0.jar",
          "size": 613720,
          "sha512": "5a77b33eb1f89599e60fdf3c0831c9630753da8b795950a2f7edd3ae4a7ff19ac1db081f2781d26a4b1709389b6bf12dd28b216893660b10f30daf081e3bf7f1",
          "sha256": "11b16b7b6fa6f1a4c6eab9240ba8739b7467deed09d4120c27cb293f02c058fb",
          "sha1": "c2c4159516dccb9a8c6e89302f175074f51211f9",
          "md5": "64c82167ba4a6b58fc31878fd910f1c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "com.saunhardy",
          "module": "createrington-dev-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.6.0.jar",
          "url": "crnet-2.6.0.jar",
          "size": 613720,
          "sha512": "5a77b33eb1f89599e60fdf3c0831c9630753da8b795950a2f7edd3ae4a7ff19ac1db081f2781d26a4b1709389b6bf12dd28b216893660b10f30daf081e3bf7f1",
          "sha256": "11b16b7b6fa6f1a4c6eab9240ba8739b7467deed09d4120c27cb293f02c058fb",
          "sha1": "c2c4159516dccb9a8c6e89302f175074f51211f9",
          "md5": "64c82167ba4a6b58fc31878fd910f1c0"
        }
      ]
    }
  ]
}
