{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "2.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.8.3.jar",
          "url": "crnet-2.8.3.jar",
          "size": 618437,
          "sha512": "3d348c305a86b0e1c51668fd3695b451f5e1fe91be68e30c24325f54842574b93c19b78dbb1da18940b659f5fc9332b62a1e6dd212fb77d97ef09df300d136f9",
          "sha256": "cbb01bd68be4edb73f4c96ba75df117a03f02d961eba068ce671cf6cf7cd116a",
          "sha1": "26e8b82ffcec791a8a83b431d639b1251a4547f8",
          "md5": "33d389d1788726cb890c8be6a40b1bc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.8.3.jar",
          "url": "crnet-2.8.3.jar",
          "size": 618437,
          "sha512": "3d348c305a86b0e1c51668fd3695b451f5e1fe91be68e30c24325f54842574b93c19b78dbb1da18940b659f5fc9332b62a1e6dd212fb77d97ef09df300d136f9",
          "sha256": "cbb01bd68be4edb73f4c96ba75df117a03f02d961eba068ce671cf6cf7cd116a",
          "sha1": "26e8b82ffcec791a8a83b431d639b1251a4547f8",
          "md5": "33d389d1788726cb890c8be6a40b1bc0"
        }
      ]
    }
  ]
}
