{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.8.1.jar",
          "url": "crnet-2.8.1.jar",
          "size": 618738,
          "sha512": "04a7a66d497cbd78f718e7bfbabf3e2e48b5bd4b6a9422ddbdb4a60122939cb5771316afd17fd5fc24fe49c575d0fde8248ea9d91179f295ac5d395a99a59256",
          "sha256": "134d2f769b279028a83358741e2336b3d059cab0f0e73daa6df4b135ec88785c",
          "sha1": "658d9be91281f892fd8436cecfcbf7c80e578883",
          "md5": "84bd70a446d57dd0463431788461da2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.8.1.jar",
          "url": "crnet-2.8.1.jar",
          "size": 618738,
          "sha512": "04a7a66d497cbd78f718e7bfbabf3e2e48b5bd4b6a9422ddbdb4a60122939cb5771316afd17fd5fc24fe49c575d0fde8248ea9d91179f295ac5d395a99a59256",
          "sha256": "134d2f769b279028a83358741e2336b3d059cab0f0e73daa6df4b135ec88785c",
          "sha1": "658d9be91281f892fd8436cecfcbf7c80e578883",
          "md5": "84bd70a446d57dd0463431788461da2c"
        }
      ]
    }
  ]
}
