{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crnet-2.2.0.jar",
          "url": "crnet-2.2.0.jar",
          "size": 580717,
          "sha512": "aac6674b79cd57edbb31e6c430b5414bcf5c82634ec07db3d419c6f8893a4661d2d698c5a6e3d0a4d3701192f47abf5bdc3806f1c6b7fab5bf0da70287b90014",
          "sha256": "7dc50f87b51cc7b726bf106f5cc73f40ed3de41723719a45ccea0bf3cf7edae7",
          "sha1": "bd7023cd59004689a42c71d443a99f64bf415ee2",
          "md5": "c82f873df7415513ccaf10e4ef314fd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.2.0.jar",
          "url": "crnet-2.2.0.jar",
          "size": 580717,
          "sha512": "aac6674b79cd57edbb31e6c430b5414bcf5c82634ec07db3d419c6f8893a4661d2d698c5a6e3d0a4d3701192f47abf5bdc3806f1c6b7fab5bf0da70287b90014",
          "sha256": "7dc50f87b51cc7b726bf106f5cc73f40ed3de41723719a45ccea0bf3cf7edae7",
          "sha1": "bd7023cd59004689a42c71d443a99f64bf415ee2",
          "md5": "c82f873df7415513ccaf10e4ef314fd7"
        }
      ]
    }
  ]
}
