{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-3.0.1.jar",
          "url": "crnet-3.0.1.jar",
          "size": 617289,
          "sha512": "3fb6fea293d85f79919e6e2773634ad011017e3adde72b4e3dccc2100ede3db1e4e3f721c26bd7c062a8a6e4700ace65a4ddf7f0b48780ddadbd9ae94e3520ff",
          "sha256": "28917903a6600abfbb20847376e4b771a937816baaf639e6cc036b35c2dbe25b",
          "sha1": "e795724c937dde9449d3fed0e47a40dd1da75bf8",
          "md5": "6a0892b026d597712bcb416a3194a154"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "com.saunhardy",
          "module": "createrington-api",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-3.0.1.jar",
          "url": "crnet-3.0.1.jar",
          "size": 617289,
          "sha512": "3fb6fea293d85f79919e6e2773634ad011017e3adde72b4e3dccc2100ede3db1e4e3f721c26bd7c062a8a6e4700ace65a4ddf7f0b48780ddadbd9ae94e3520ff",
          "sha256": "28917903a6600abfbb20847376e4b771a937816baaf639e6cc036b35c2dbe25b",
          "sha1": "e795724c937dde9449d3fed0e47a40dd1da75bf8",
          "md5": "6a0892b026d597712bcb416a3194a154"
        }
      ]
    }
  ]
}
