{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "createrington-api",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "createrington-api-1.3.0.jar",
          "url": "createrington-api-1.3.0.jar",
          "size": 39712,
          "sha512": "ff07ace6d9a4b05c39fbef76539388a50a6749bb1bcb47e420d6b623f3d059652cbdb83311fed1c54ac111b1965bdf307319a803e35020432806c20e048f0463",
          "sha256": "63bba4ec09eb65205f2d5c7227fc50d244e0a59684b6b4662dda29e351d0b032",
          "sha1": "706f06c85ded031742d20063bfab64e6463d4d97",
          "md5": "958fd688868d0cdada7af2a2907f5f33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createrington-api-1.3.0.jar",
          "url": "createrington-api-1.3.0.jar",
          "size": 39712,
          "sha512": "ff07ace6d9a4b05c39fbef76539388a50a6749bb1bcb47e420d6b623f3d059652cbdb83311fed1c54ac111b1965bdf307319a803e35020432806c20e048f0463",
          "sha256": "63bba4ec09eb65205f2d5c7227fc50d244e0a59684b6b4662dda29e351d0b032",
          "sha1": "706f06c85ded031742d20063bfab64e6463d4d97",
          "md5": "958fd688868d0cdada7af2a2907f5f33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createrington-api-1.3.0-sources.jar",
          "url": "createrington-api-1.3.0-sources.jar",
          "size": 15390,
          "sha512": "47474ccfc8914db8fc386e34562587f78b6e6c55eeaadc36d653f1d6785dad7ff617b5907042fc680e45543be80fe3ffd2f48014bb9dc60e65e6c950e1c533e2",
          "sha256": "b162534c94368af3064bffa8a7d1c4444255a6b86c22447f48bf62b8bb630950",
          "sha1": "802e04ea05c360d0294da4123849e20771b610ac",
          "md5": "eb33188d76f330cb5d493059096b0d59"
        }
      ]
    }
  ]
}
