{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crnet-2.1.1.jar",
          "url": "crnet-2.1.1.jar",
          "size": 33369,
          "sha512": "a605309f9dff84a4b670ff7925fc2d9c46c072d401f123dd47aa1ced246525bbdbf660e0d9b19cb5bae9be26d225baf2e474124f3cc23f585ecf0e8911019027",
          "sha256": "57116d955b9e991235b4978e7e234875718ba985442b31744d62efcbaa304af3",
          "sha1": "b6848ac4b93502e777bce4aacb1512cde69b8247",
          "md5": "df8beea46fee1a1d4316ab65b3da4d6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.1.1.jar",
          "url": "crnet-2.1.1.jar",
          "size": 33369,
          "sha512": "a605309f9dff84a4b670ff7925fc2d9c46c072d401f123dd47aa1ced246525bbdbf660e0d9b19cb5bae9be26d225baf2e474124f3cc23f585ecf0e8911019027",
          "sha256": "57116d955b9e991235b4978e7e234875718ba985442b31744d62efcbaa304af3",
          "sha1": "b6848ac4b93502e777bce4aacb1512cde69b8247",
          "md5": "df8beea46fee1a1d4316ab65b3da4d6b"
        }
      ]
    }
  ]
}
