{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crnet-2.1.2.jar",
          "url": "crnet-2.1.2.jar",
          "size": 33839,
          "sha512": "77ca1ead349ad55560938b36fbcf2fa2220a4d08ea597dc532ece368a3567577fde0249dd1b967a7303f7920553f177d4935f68d63c28adec2c823ab983ee340",
          "sha256": "35e4c43ac1e9b2aaa9d8a7c1fd63091ecbf8abb7081071253ee17324a4f98b8b",
          "sha1": "295b21880edceca17cdf20f97881d78021243e70",
          "md5": "5ca8ed4187836e6250773b6e0a33be08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.1.2.jar",
          "url": "crnet-2.1.2.jar",
          "size": 33839,
          "sha512": "77ca1ead349ad55560938b36fbcf2fa2220a4d08ea597dc532ece368a3567577fde0249dd1b967a7303f7920553f177d4935f68d63c28adec2c823ab983ee340",
          "sha256": "35e4c43ac1e9b2aaa9d8a7c1fd63091ecbf8abb7081071253ee17324a4f98b8b",
          "sha1": "295b21880edceca17cdf20f97881d78021243e70",
          "md5": "5ca8ed4187836e6250773b6e0a33be08"
        }
      ]
    }
  ]
}
