{
  "formatVersion": "1.1",
  "component": {
    "group": "com.saunhardy",
    "module": "crnet",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crnet-2.1.2.jar",
          "url": "crnet-2.1.2.jar",
          "size": 583203,
          "sha512": "9b20fff3c15a2d6f10a36820f5caeacc6c5260fcc9c5c43e2700906cdea408942850674321ae35cb043608b43fbde78c12ff8989ee30bf06c6704ddee23b0161",
          "sha256": "0b5bfe3eb3378e11e92982085cfb8720b845f453d6258f65d3902229889ebba4",
          "sha1": "186d0e7ec1786b1da3b0a3e221f243aed996e27a",
          "md5": "f1a8e5bed39840edccb484ce29d5edf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.12.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-gson",
          "version": {
            "requires": "0.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "crnet-2.1.2.jar",
          "url": "crnet-2.1.2.jar",
          "size": 583203,
          "sha512": "9b20fff3c15a2d6f10a36820f5caeacc6c5260fcc9c5c43e2700906cdea408942850674321ae35cb043608b43fbde78c12ff8989ee30bf06c6704ddee23b0161",
          "sha256": "0b5bfe3eb3378e11e92982085cfb8720b845f453d6258f65d3902229889ebba4",
          "sha1": "186d0e7ec1786b1da3b0a3e221f243aed996e27a",
          "md5": "f1a8e5bed39840edccb484ce29d5edf3"
        }
      ]
    }
  ]
}
